package org.test.style;

import com.vaadin.server.FontIcon;

public enum MaterialIcons implements FontIcon {

    THREE_D_ROTATION(0xE84D), AC_UNIT(0xEB3B), ACCESS_ALARM(0xE190), ACCESS_ALARMS(0xE191), ACCESS_TIME(
            0xE192), ACCESSIBILITY(0xE84E), ACCESSIBLE(0xE914), ACCOUNT_BALANCE(0xE84F), ACCOUNT_BALANCE_WALLET(
            0xE850), ACCOUNT_BOX(0xE851), ACCOUNT_CIRCLE(0xE853), ADB(0xE60E), ADD(0xE145), ADD_A_PHOTO(
            0xE439), ADD_ALARM(0xE193), ADD_ALERT(0xE003), ADD_BOX(0xE146), ADD_CIRCLE(
            0xE147), ADD_CIRCLE_OUTLINE(0xE148), ADD_LOCATION(0xE567), ADD_SHOPPING_CART(
            0xE854), ADD_TO_PHOTOS(0xE39D), ADD_TO_QUEUE(0xE05C), ADJUST(
            0xE39E), AIRLINE_SEAT_FLAT(0xE630), AIRLINE_SEAT_FLAT_ANGLED(
            0xE631), AIRLINE_SEAT_INDIVIDUAL_SUITE(
            0xE632), AIRLINE_SEAT_LEGROOM_EXTRA(
            0xE633), AIRLINE_SEAT_LEGROOM_NORMAL(
            0xE634), AIRLINE_SEAT_LEGROOM_REDUCED(
            0xE635), AIRLINE_SEAT_RECLINE_EXTRA(
            0xE636), AIRLINE_SEAT_RECLINE_NORMAL(
            0xE637), AIRPLANEMODE_ACTIVE(
            0xE195), AIRPLANEMODE_INACTIVE(
            0xE194), AIRPLAY(
            0xE055), AIRPORT_SHUTTLE(
            0xEB3C), ALARM(
            0xE855), ALARM_ADD(
            0xE856), ALARM_OFF(
            0xE857), ALARM_ON(
            0xE858), ALBUM(
            0xE019), ALL_INCLUSIVE(
            0xEB3D), ALL_OUT(
            0xE90B), ANDROID(
            0xE859), ANNOUNCEMENT(
            0xE85A), APPS(
            0xE5C3), ARCHIVE(
            0xE149), ARROW_BACK(
            0xE5C4), ARROW_DOWNWARD(
            0xE5DB), ARROW_DROP_DOWN(
            0xE5C5), ARROW_DROP_DOWN_CIRCLE(
            0xE5C6), ARROW_DROP_UP(
            0xE5C7), ARROW_FORWARD(
            0xE5C8), ARROW_UPWARD(
            0xE5D8), ART_TRACK(
            0xE060), ASPECT_RATIO(
            0xE85B), ASSESSMENT(
            0xE85C), ASSIGNMENT(
            0xE85D), ASSIGNMENT_IND(
            0xE85E), ASSIGNMENT_LATE(
            0xE85F), ASSIGNMENT_RETURN(
            0xE860), ASSIGNMENT_RETURNED(
            0xE861), ASSIGNMENT_TURNED_IN(
            0xE862), ASSISTANT(
            0xE39F), ASSISTANT_PHOTO(
            0xE3A0), ATTACH_FILE(
            0xE226), ATTACH_MONEY(
            0xE227), ATTACHMENT(
            0xE2BC), AUDIOTRACK(
            0xE3A1), AUTORENEW(
            0xE863), AV_TIMER(
            0xE01B), BACKSPACE(
            0xE14A), BACKUP(
            0xE864), BATTERY_ALERT(
            0xE19C), BATTERY_CHARGING_FULL(
            0xE1A3), BATTERY_FULL(
            0xE1A4), BATTERY_STD(
            0xE1A5), BATTERY_UNKNOWN(
            0xE1A6), BEACH_ACCESS(
            0xEB3E), BEENHERE(
            0xE52D), BLOCK(
            0xE14B), BLUETOOTH(
            0xE1A7), BLUETOOTH_AUDIO(
            0xE60F), BLUETOOTH_CONNECTED(
            0xE1A8), BLUETOOTH_DISABLED(
            0xE1A9), BLUETOOTH_SEARCHING(
            0xE1AA), BLUR_CIRCULAR(
            0xE3A2), BLUR_LINEAR(
            0xE3A3), BLUR_OFF(
            0xE3A4), BLUR_ON(
            0xE3A5), BOOK(
            0xE865), BOOKMARK(
            0xE866), BOOKMARK_BORDER(
            0xE867), BORDER_ALL(
            0xE228), BORDER_BOTTOM(
            0xE229), BORDER_CLEAR(
            0xE22A), BORDER_COLOR(
            0xE22B), BORDER_HORIZONTAL(
            0xE22C), BORDER_INNER(
            0xE22D), BORDER_LEFT(
            0xE22E), BORDER_OUTER(
            0xE22F), BORDER_RIGHT(
            0xE230), BORDER_STYLE(
            0xE231), BORDER_TOP(
            0xE232), BORDER_VERTICAL(
            0xE233), BRANDING_WATERMARK(
            0xE06B), BRIGHTNESS_1(
            0xE3A6), BRIGHTNESS_2(
            0xE3A7), BRIGHTNESS_3(
            0xE3A8), BRIGHTNESS_4(
            0xE3A9), BRIGHTNESS_5(
            0xE3AA), BRIGHTNESS_6(
            0xE3AB), BRIGHTNESS_7(
            0xE3AC), BRIGHTNESS_AUTO(
            0xE1AB), BRIGHTNESS_HIGH(
            0xE1AC), BRIGHTNESS_LOW(
            0xE1AD), BRIGHTNESS_MEDIUM(
            0xE1AE), BROKEN_IMAGE(
            0xE3AD), BRUSH(
            0xE3AE), BUBBLE_CHART(
            0xE6DD), BUG_REPORT(
            0xE868), BUILD(
            0xE869), BURST_MODE(
            0xE43C), BUSINESS(
            0xE0AF), BUSINESS_CENTER(
            0xEB3F), CACHED(
            0xE86A), CAKE(
            0xE7E9), CALL(
            0xE0B0), CALL_END(
            0xE0B1), CALL_MADE(
            0xE0B2), CALL_MERGE(
            0xE0B3), CALL_MISSED(
            0xE0B4), CALL_MISSED_OUTGOING(
            0xE0E4), CALL_RECEIVED(
            0xE0B5), CALL_SPLIT(
            0xE0B6), CALL_TO_ACTION(
            0xE06C), CAMERA(
            0xE3AF), CAMERA_ALT(
            0xE3B0), CAMERA_ENHANCE(
            0xE8FC), CAMERA_FRONT(
            0xE3B1), CAMERA_REAR(
            0xE3B2), CAMERA_ROLL(
            0xE3B3), CANCEL(
            0xE5C9), CARD_GIFTCARD(
            0xE8F6), CARD_MEMBERSHIP(
            0xE8F7), CARD_TRAVEL(
            0xE8F8), CASINO(
            0xEB40), CAST(
            0xE307), CAST_CONNECTED(
            0xE308), CENTER_FOCUS_STRONG(
            0xE3B4), CENTER_FOCUS_WEAK(
            0xE3B5), CHANGE_HISTORY(
            0xE86B), CHAT(
            0xE0B7), CHAT_BUBBLE(
            0xE0CA), CHAT_BUBBLE_OUTLINE(
            0xE0CB), CHECK(
            0xE5CA), CHECK_BOX(
            0xE834), CHECK_BOX_OUTLINE_BLANK(
            0xE835), CHECK_CIRCLE(
            0xE86C), CHEVRON_LEFT(
            0xE5CB), CHEVRON_RIGHT(
            0xE5CC), CHILD_CARE(
            0xEB41), CHILD_FRIENDLY(
            0xEB42), CHROME_READER_MODE(
            0xE86D), CLASS(
            0xE86E), CLEAR(
            0xE14C), CLEAR_ALL(
            0xE0B8), CLOSE(
            0xE5CD), CLOSED_CAPTION(
            0xE01C), CLOUD(
            0xE2BD), CLOUD_CIRCLE(
            0xE2BE), CLOUD_DONE(
            0xE2BF), CLOUD_DOWNLOAD(
            0xE2C0), CLOUD_OFF(
            0xE2C1), CLOUD_QUEUE(
            0xE2C2), CLOUD_UPLOAD(
            0xE2C3), CODE(
            0xE86F), COLLECTIONS(
            0xE3B6), COLLECTIONS_BOOKMARK(
            0xE431), COLOR_LENS(
            0xE3B7), COLORIZE(
            0xE3B8), COMMENT(
            0xE0B9), COMPARE(
            0xE3B9), COMPARE_ARROWS(
            0xE915), COMPUTER(
            0xE30A), CONFIRMATION_NUMBER(
            0xE638), CONTACT_MAIL(
            0xE0D0), CONTACT_PHONE(
            0xE0CF), CONTACTS(
            0xE0BA), CONTENT_COPY(
            0xE14D), CONTENT_CUT(
            0xE14E), CONTENT_PASTE(
            0xE14F), CONTROL_POINT(
            0xE3BA), CONTROL_POINT_DUPLICATE(
            0xE3BB), COPYRIGHT(
            0xE90C), CREATE(
            0xE150), CREATE_NEW_FOLDER(
            0xE2CC), CREDIT_CARD(
            0xE870), CROP(
            0xE3BE), CROP_16_9(
            0xE3BC), CROP_3_2(
            0xE3BD), CROP_5_4(
            0xE3BF), CROP_7_5(
            0xE3C0), CROP_DIN(
            0xE3C1), CROP_FREE(
            0xE3C2), CROP_LANDSCAPE(
            0xE3C3), CROP_ORIGINAL(
            0xE3C4), CROP_PORTRAIT(
            0xE3C5), CROP_ROTATE(
            0xE437), CROP_SQUARE(
            0xE3C6), DASHBOARD(
            0xE871), DATA_USAGE(
            0xE1AF), DATE_RANGE(
            0xE916), DEHAZE(
            0xE3C7), DELETE(
            0xE872), DELETE_FOREVER(
            0xE92B), DELETE_SWEEP(
            0xE16C), DESCRIPTION(
            0xE873), DESKTOP_MAC(
            0xE30B), DESKTOP_WINDOWS(
            0xE30C), DETAILS(
            0xE3C8), DEVELOPER_BOARD(
            0xE30D), DEVELOPER_MODE(
            0xE1B0), DEVICE_HUB(
            0xE335), DEVICES(
            0xE1B1), DEVICES_OTHER(
            0xE337), DIALER_SIP(
            0xE0BB), DIALPAD(
            0xE0BC), DIRECTIONS(
            0xE52E), DIRECTIONS_BIKE(
            0xE52F), DIRECTIONS_BOAT(
            0xE532), DIRECTIONS_BUS(
            0xE530), DIRECTIONS_CAR(
            0xE531), DIRECTIONS_RAILWAY(
            0xE534), DIRECTIONS_RUN(
            0xE566), DIRECTIONS_SUBWAY(
            0xE533), DIRECTIONS_TRANSIT(
            0xE535), DIRECTIONS_WALK(
            0xE536), DISC_FULL(
            0xE610), DNS(
            0xE875), DO_NOT_DISTURB(
            0xE612), DO_NOT_DISTURB_ALT(
            0xE611), DO_NOT_DISTURB_OFF(
            0xE643), DO_NOT_DISTURB_ON(
            0xE644), DOCK(
            0xE30E), DOMAIN(
            0xE7EE), DONE(
            0xE876), DONE_ALL(
            0xE877), DONUT_LARGE(
            0xE917), DONUT_SMALL(
            0xE918), DRAFTS(
            0xE151), DRAG_HANDLE(
            0xE25D), DRIVE_ETA(
            0xE613), DVR(
            0xE1B2), EDIT(
            0xE3C9), EDIT_LOCATION(
            0xE568), EJECT(
            0xE8FB), EMAIL(
            0xE0BE), ENHANCED_ENCRYPTION(
            0xE63F), EQUALIZER(
            0xE01D), ERROR(
            0xE000), ERROR_OUTLINE(
            0xE001), EURO_SYMBOL(
            0xE926), EV_STATION(
            0xE56D), EVENT(
            0xE878), EVENT_AVAILABLE(
            0xE614), EVENT_BUSY(
            0xE615), EVENT_NOTE(
            0xE616), EVENT_SEAT(
            0xE903), EXIT_TO_APP(
            0xE879), EXPAND_LESS(
            0xE5CE), EXPAND_MORE(
            0xE5CF), EXPLICIT(
            0xE01E), EXPLORE(
            0xE87A), EXPOSURE(
            0xE3CA), EXPOSURE_NEG_1(
            0xE3CB), EXPOSURE_NEG_2(
            0xE3CC), EXPOSURE_PLUS_1(
            0xE3CD), EXPOSURE_PLUS_2(
            0xE3CE), EXPOSURE_ZERO(
            0xE3CF), EXTENSION(
            0xE87B), FACE(
            0xE87C), FAST_FORWARD(
            0xE01F), FAST_REWIND(
            0xE020), FAVORITE(
            0xE87D), FAVORITE_BORDER(
            0xE87E), FEATURED_PLAY_LIST(
            0xE06D), FEATURED_VIDEO(
            0xE06E), FEEDBACK(
            0xE87F), FIBER_DVR(
            0xE05D), FIBER_MANUAL_RECORD(
            0xE061), FIBER_NEW(
            0xE05E), FIBER_PIN(
            0xE06A), FIBER_SMART_RECORD(
            0xE062), FILE_DOWNLOAD(
            0xE2C4), FILE_UPLOAD(
            0xE2C6), FILTER(
            0xE3D3), FILTER_1(
            0xE3D0), FILTER_2(
            0xE3D1), FILTER_3(
            0xE3D2), FILTER_4(
            0xE3D4), FILTER_5(
            0xE3D5), FILTER_6(
            0xE3D6), FILTER_7(
            0xE3D7), FILTER_8(
            0xE3D8), FILTER_9(
            0xE3D9), FILTER_9_PLUS(
            0xE3DA), FILTER_B_AND_W(
            0xE3DB), FILTER_CENTER_FOCUS(
            0xE3DC), FILTER_DRAMA(
            0xE3DD), FILTER_FRAMES(
            0xE3DE), FILTER_HDR(
            0xE3DF), FILTER_LIST(
            0xE152), FILTER_NONE(
            0xE3E0), FILTER_TILT_SHIFT(
            0xE3E2), FILTER_VINTAGE(
            0xE3E3), FIND_IN_PAGE(
            0xE880), FIND_REPLACE(
            0xE881), FINGERPRINT(
            0xE90D), FIRST_PAGE(
            0xE5DC), FITNESS_CENTER(
            0xEB43), FLAG(
            0xE153), FLARE(
            0xE3E4), FLASH_AUTO(
            0xE3E5), FLASH_OFF(
            0xE3E6), FLASH_ON(
            0xE3E7), FLIGHT(
            0xE539), FLIGHT_LAND(
            0xE904), FLIGHT_TAKEOFF(
            0xE905), FLIP(
            0xE3E8), FLIP_TO_BACK(
            0xE882), FLIP_TO_FRONT(
            0xE883), FOLDER(
            0xE2C7), FOLDER_OPEN(
            0xE2C8), FOLDER_SHARED(
            0xE2C9), FOLDER_SPECIAL(
            0xE617), FONT_DOWNLOAD(
            0xE167), FORMAT_ALIGN_CENTER(
            0xE234), FORMAT_ALIGN_JUSTIFY(
            0xE235), FORMAT_ALIGN_LEFT(
            0xE236), FORMAT_ALIGN_RIGHT(
            0xE237), FORMAT_BOLD(
            0xE238), FORMAT_CLEAR(
            0xE239), FORMAT_COLOR_FILL(
            0xE23A), FORMAT_COLOR_RESET(
            0xE23B), FORMAT_COLOR_TEXT(
            0xE23C), FORMAT_INDENT_DECREASE(
            0xE23D), FORMAT_INDENT_INCREASE(
            0xE23E), FORMAT_ITALIC(
            0xE23F), FORMAT_LINE_SPACING(
            0xE240), FORMAT_LIST_BULLETED(
            0xE241), FORMAT_LIST_NUMBERED(
            0xE242), FORMAT_PAINT(
            0xE243), FORMAT_QUOTE(
            0xE244), FORMAT_SHAPES(
            0xE25E), FORMAT_SIZE(
            0xE245), FORMAT_STRIKETHROUGH(
            0xE246), FORMAT_TEXTDIRECTION_L_TO_R(
            0xE247), FORMAT_TEXTDIRECTION_R_TO_L(
            0xE248), FORMAT_UNDERLINED(
            0xE249), FORUM(
            0xE0BF), FORWARD(
            0xE154), FORWARD_10(
            0xE056), FORWARD_30(
            0xE057), FORWARD_5(
            0xE058), FREE_BREAKFAST(
            0xEB44), FULLSCREEN(
            0xE5D0), FULLSCREEN_EXIT(
            0xE5D1), FUNCTIONS(
            0xE24A), G_TRANSLATE(
            0xE927), GAMEPAD(
            0xE30F), GAMES(
            0xE021), GAVEL(
            0xE90E), GESTURE(
            0xE155), GET_APP(
            0xE884), GIF(
            0xE908), GOLF_COURSE(
            0xEB45), GPS_FIXED(
            0xE1B3), GPS_NOT_FIXED(
            0xE1B4), GPS_OFF(
            0xE1B5), GRADE(
            0xE885), GRADIENT(
            0xE3E9), GRAIN(
            0xE3EA), GRAPHIC_EQ(
            0xE1B8), GRID_OFF(
            0xE3EB), GRID_ON(
            0xE3EC), GROUP(
            0xE7EF), GROUP_ADD(
            0xE7F0), GROUP_WORK(
            0xE886), HD(
            0xE052), HDR_OFF(
            0xE3ED), HDR_ON(
            0xE3EE), HDR_STRONG(
            0xE3F1), HDR_WEAK(
            0xE3F2), HEADSET(
            0xE310), HEADSET_MIC(
            0xE311), HEALING(
            0xE3F3), HEARING(
            0xE023), HELP(
            0xE887), HELP_OUTLINE(
            0xE8FD), HIGH_QUALITY(
            0xE024), HIGHLIGHT(
            0xE25F), HIGHLIGHT_OFF(
            0xE888), HISTORY(
            0xE889), HOME(
            0xE88A), HOT_TUB(
            0xEB46), HOTEL(
            0xE53A), HOURGLASS_EMPTY(
            0xE88B), HOURGLASS_FULL(
            0xE88C), HTTP(
            0xE902), HTTPS(
            0xE88D), IMAGE(
            0xE3F4), IMAGE_ASPECT_RATIO(
            0xE3F5), IMPORT_CONTACTS(
            0xE0E0), IMPORT_EXPORT(
            0xE0C3), IMPORTANT_DEVICES(
            0xE912), INBOX(
            0xE156), INDETERMINATE_CHECK_BOX(
            0xE909), INFO(
            0xE88E), INFO_OUTLINE(
            0xE88F), INPUT(
            0xE890), INSERT_CHART(
            0xE24B), INSERT_COMMENT(
            0xE24C), INSERT_DRIVE_FILE(
            0xE24D), INSERT_EMOTICON(
            0xE24E), INSERT_INVITATION(
            0xE24F), INSERT_LINK(
            0xE250), INSERT_PHOTO(
            0xE251), INVERT_COLORS(
            0xE891), INVERT_COLORS_OFF(
            0xE0C4), ISO(
            0xE3F6), KEYBOARD(
            0xE312), KEYBOARD_ARROW_DOWN(
            0xE313), KEYBOARD_ARROW_LEFT(
            0xE314), KEYBOARD_ARROW_RIGHT(
            0xE315), KEYBOARD_ARROW_UP(
            0xE316), KEYBOARD_BACKSPACE(
            0xE317), KEYBOARD_CAPSLOCK(
            0xE318), KEYBOARD_HIDE(
            0xE31A), KEYBOARD_RETURN(
            0xE31B), KEYBOARD_TAB(
            0xE31C), KEYBOARD_VOICE(
            0xE31D), KITCHEN(
            0xEB47), LABEL(
            0xE892), LABEL_OUTLINE(
            0xE893), LANDSCAPE(
            0xE3F7), LANGUAGE(
            0xE894), LAPTOP(
            0xE31E), LAPTOP_CHROMEBOOK(
            0xE31F), LAPTOP_MAC(
            0xE320), LAPTOP_WINDOWS(
            0xE321), LAST_PAGE(
            0xE5DD), LAUNCH(
            0xE895), LAYERS(
            0xE53B), LAYERS_CLEAR(
            0xE53C), LEAK_ADD(
            0xE3F8), LEAK_REMOVE(
            0xE3F9), LENS(
            0xE3FA), LIBRARY_ADD(
            0xE02E), LIBRARY_BOOKS(
            0xE02F), LIBRARY_MUSIC(
            0xE030), LIGHTBULB_OUTLINE(
            0xE90F), LINE_STYLE(
            0xE919), LINE_WEIGHT(
            0xE91A), LINEAR_SCALE(
            0xE260), LINK(
            0xE157), LINKED_CAMERA(
            0xE438), LIST(
            0xE896), LIVE_HELP(
            0xE0C6), LIVE_TV(
            0xE639), LOCAL_ACTIVITY(
            0xE53F), LOCAL_AIRPORT(
            0xE53D), LOCAL_ATM(
            0xE53E), LOCAL_BAR(
            0xE540), LOCAL_CAFE(
            0xE541), LOCAL_CAR_WASH(
            0xE542), LOCAL_CONVENIENCE_STORE(
            0xE543), LOCAL_DINING(
            0xE556), LOCAL_DRINK(
            0xE544), LOCAL_FLORIST(
            0xE545), LOCAL_GAS_STATION(
            0xE546), LOCAL_GROCERY_STORE(
            0xE547), LOCAL_HOSPITAL(
            0xE548), LOCAL_HOTEL(
            0xE549), LOCAL_LAUNDRY_SERVICE(
            0xE54A), LOCAL_LIBRARY(
            0xE54B), LOCAL_MALL(
            0xE54C), LOCAL_MOVIES(
            0xE54D), LOCAL_OFFER(
            0xE54E), LOCAL_PARKING(
            0xE54F), LOCAL_PHARMACY(
            0xE550), LOCAL_PHONE(
            0xE551), LOCAL_PIZZA(
            0xE552), LOCAL_PLAY(
            0xE553), LOCAL_POST_OFFICE(
            0xE554), LOCAL_PRINTSHOP(
            0xE555), LOCAL_SEE(
            0xE557), LOCAL_SHIPPING(
            0xE558), LOCAL_TAXI(
            0xE559), LOCATION_CITY(
            0xE7F1), LOCATION_DISABLED(
            0xE1B6), LOCATION_OFF(
            0xE0C7), LOCATION_ON(
            0xE0C8), LOCATION_SEARCHING(
            0xE1B7), LOCK(
            0xE897), LOCK_OPEN(
            0xE898), LOCK_OUTLINE(
            0xE899), LOOKS(
            0xE3FC), LOOKS_3(
            0xE3FB), LOOKS_4(
            0xE3FD), LOOKS_5(
            0xE3FE), LOOKS_6(
            0xE3FF), LOOKS_ONE(
            0xE400), LOOKS_TWO(
            0xE401), LOOP(
            0xE028), LOUPE(
            0xE402), LOW_PRIORITY(
            0xE16D), LOYALTY(
            0xE89A), MAIL(
            0xE158), MAIL_OUTLINE(
            0xE0E1), MAP(
            0xE55B), MARKUNREAD(
            0xE159), MARKUNREAD_MAILBOX(
            0xE89B), MEMORY(
            0xE322), MENU(
            0xE5D2), MERGE_TYPE(
            0xE252), MESSAGE(
            0xE0C9), MIC(
            0xE029), MIC_NONE(
            0xE02A), MIC_OFF(
            0xE02B), MMS(
            0xE618), MODE_COMMENT(
            0xE253), MODE_EDIT(
            0xE254), MONETIZATION_ON(
            0xE263), MONEY_OFF(
            0xE25C), MONOCHROME_PHOTOS(
            0xE403), MOOD(
            0xE7F2), MOOD_BAD(
            0xE7F3), MORE(
            0xE619), MORE_HORIZ(
            0xE5D3), MORE_VERT(
            0xE5D4), MOTORCYCLE(
            0xE91B), MOUSE(
            0xE323), MOVE_TO_INBOX(
            0xE168), MOVIE(
            0xE02C), MOVIE_CREATION(
            0xE404), MOVIE_FILTER(
            0xE43A), MULTILINE_CHART(
            0xE6DF), MUSIC_NOTE(
            0xE405), MUSIC_VIDEO(
            0xE063), MY_LOCATION(
            0xE55C), NATURE(
            0xE406), NATURE_PEOPLE(
            0xE407), NAVIGATE_BEFORE(
            0xE408), NAVIGATE_NEXT(
            0xE409), NAVIGATION(
            0xE55D), NEAR_ME(
            0xE569), NETWORK_CELL(
            0xE1B9), NETWORK_CHECK(
            0xE640), NETWORK_LOCKED(
            0xE61A), NETWORK_WIFI(
            0xE1BA), NEW_RELEASES(
            0xE031), NEXT_WEEK(
            0xE16A), NFC(
            0xE1BB), NO_ENCRYPTION(
            0xE641), NO_SIM(
            0xE0CC), NOT_INTERESTED(
            0xE033), NOTE(
            0xE06F), NOTE_ADD(
            0xE89C), NOTIFICATIONS(
            0xE7F4), NOTIFICATIONS_ACTIVE(
            0xE7F7), NOTIFICATIONS_NONE(
            0xE7F5), NOTIFICATIONS_OFF(
            0xE7F6), NOTIFICATIONS_PAUSED(
            0xE7F8), OFFLINE_PIN(
            0xE90A), ONDEMAND_VIDEO(
            0xE63A), OPACITY(
            0xE91C), OPEN_IN_BROWSER(
            0xE89D), OPEN_IN_NEW(
            0xE89E), OPEN_WITH(
            0xE89F), PAGES(
            0xE7F9), PAGEVIEW(
            0xE8A0), PALETTE(
            0xE40A), PAN_TOOL(
            0xE925), PANORAMA(
            0xE40B), PANORAMA_FISH_EYE(
            0xE40C), PANORAMA_HORIZONTAL(
            0xE40D), PANORAMA_VERTICAL(
            0xE40E), PANORAMA_WIDE_ANGLE(
            0xE40F), PARTY_MODE(
            0xE7FA), PAUSE(
            0xE034), PAUSE_CIRCLE_FILLED(
            0xE035), PAUSE_CIRCLE_OUTLINE(
            0xE036), PAYMENT(
            0xE8A1), PEOPLE(
            0xE7FB), PEOPLE_OUTLINE(
            0xE7FC), PERM_CAMERA_MIC(
            0xE8A2), PERM_CONTACT_CALENDAR(
            0xE8A3), PERM_DATA_SETTING(
            0xE8A4), PERM_DEVICE_INFORMATION(
            0xE8A5), PERM_IDENTITY(
            0xE8A6), PERM_MEDIA(
            0xE8A7), PERM_PHONE_MSG(
            0xE8A8), PERM_SCAN_WIFI(
            0xE8A9), PERSON(
            0xE7FD), PERSON_ADD(
            0xE7FE), PERSON_OUTLINE(
            0xE7FF), PERSON_PIN(
            0xE55A), PERSON_PIN_CIRCLE(
            0xE56A), PERSONAL_VIDEO(
            0xE63B), PETS(
            0xE91D), PHONE(
            0xE0CD), PHONE_ANDROID(
            0xE324), PHONE_BLUETOOTH_SPEAKER(
            0xE61B), PHONE_FORWARDED(
            0xE61C), PHONE_IN_TALK(
            0xE61D), PHONE_IPHONE(
            0xE325), PHONE_LOCKED(
            0xE61E), PHONE_MISSED(
            0xE61F), PHONE_PAUSED(
            0xE620), PHONELINK(
            0xE326), PHONELINK_ERASE(
            0xE0DB), PHONELINK_LOCK(
            0xE0DC), PHONELINK_OFF(
            0xE327), PHONELINK_RING(
            0xE0DD), PHONELINK_SETUP(
            0xE0DE), PHOTO(
            0xE410), PHOTO_ALBUM(
            0xE411), PHOTO_CAMERA(
            0xE412), PHOTO_FILTER(
            0xE43B), PHOTO_LIBRARY(
            0xE413), PHOTO_SIZE_SELECT_ACTUAL(
            0xE432), PHOTO_SIZE_SELECT_LARGE(
            0xE433), PHOTO_SIZE_SELECT_SMALL(
            0xE434), PICTURE_AS_PDF(
            0xE415), PICTURE_IN_PICTURE(
            0xE8AA), PICTURE_IN_PICTURE_ALT(
            0xE911), PIE_CHART(
            0xE6C4), PIE_CHART_OUTLINED(
            0xE6C5), PIN_DROP(
            0xE55E), PLACE(
            0xE55F), PLAY_ARROW(
            0xE037), PLAY_CIRCLE_FILLED(
            0xE038), PLAY_CIRCLE_OUTLINE(
            0xE039), PLAY_FOR_WORK(
            0xE906), PLAYLIST_ADD(
            0xE03B), PLAYLIST_ADD_CHECK(
            0xE065), PLAYLIST_PLAY(
            0xE05F), PLUS_ONE(
            0xE800), POLL(
            0xE801), POLYMER(
            0xE8AB), POOL(
            0xEB48), PORTABLE_WIFI_OFF(
            0xE0CE), PORTRAIT(
            0xE416), POWER(
            0xE63C), POWER_INPUT(
            0xE336), POWER_SETTINGS_NEW(
            0xE8AC), PREGNANT_WOMAN(
            0xE91E), PRESENT_TO_ALL(
            0xE0DF), PRINT(
            0xE8AD), PRIORITY_HIGH(
            0xE645), PUBLIC(
            0xE80B), PUBLISH(
            0xE255), QUERY_BUILDER(
            0xE8AE), QUESTION_ANSWER(
            0xE8AF), QUEUE(
            0xE03C), QUEUE_MUSIC(
            0xE03D), QUEUE_PLAY_NEXT(
            0xE066), RADIO(
            0xE03E), RADIO_BUTTON_CHECKED(
            0xE837), RADIO_BUTTON_UNCHECKED(
            0xE836), RATE_REVIEW(
            0xE560), RECEIPT(
            0xE8B0), RECENT_ACTORS(
            0xE03F), RECORD_VOICE_OVER(
            0xE91F), REDEEM(
            0xE8B1), REDO(
            0xE15A), REFRESH(
            0xE5D5), REMOVE(
            0xE15B), REMOVE_CIRCLE(
            0xE15C), REMOVE_CIRCLE_OUTLINE(
            0xE15D), REMOVE_FROM_QUEUE(
            0xE067), REMOVE_RED_EYE(
            0xE417), REMOVE_SHOPPING_CART(
            0xE928), REORDER(
            0xE8FE), REPEAT(
            0xE040), REPEAT_ONE(
            0xE041), REPLAY(
            0xE042), REPLAY_10(
            0xE059), REPLAY_30(
            0xE05A), REPLAY_5(
            0xE05B), REPLY(
            0xE15E), REPLY_ALL(
            0xE15F), REPORT(
            0xE160), REPORT_PROBLEM(
            0xE8B2), RESTAURANT(
            0xE56C), RESTAURANT_MENU(
            0xE561), RESTORE(
            0xE8B3), RESTORE_PAGE(
            0xE929), RING_VOLUME(
            0xE0D1), ROOM(
            0xE8B4), ROOM_SERVICE(
            0xEB49), ROTATE_90_DEGREES_CCW(
            0xE418), ROTATE_LEFT(
            0xE419), ROTATE_RIGHT(
            0xE41A), ROUNDED_CORNER(
            0xE920), ROUTER(
            0xE328), ROWING(
            0xE921), RSS_FEED(
            0xE0E5), RV_HOOKUP(
            0xE642), SATELLITE(
            0xE562), SAVE(
            0xE161), SCANNER(
            0xE329), SCHEDULE(
            0xE8B5), SCHOOL(
            0xE80C), SCREEN_LOCK_LANDSCAPE(
            0xE1BE), SCREEN_LOCK_PORTRAIT(
            0xE1BF), SCREEN_LOCK_ROTATION(
            0xE1C0), SCREEN_ROTATION(
            0xE1C1), SCREEN_SHARE(
            0xE0E2), SD_CARD(
            0xE623), SD_STORAGE(
            0xE1C2), SEARCH(
            0xE8B6), SECURITY(
            0xE32A), SELECT_ALL(
            0xE162), SEND(
            0xE163), SENTIMENT_DISSATISFIED(
            0xE811), SENTIMENT_NEUTRAL(
            0xE812), SENTIMENT_SATISFIED(
            0xE813), SENTIMENT_VERY_DISSATISFIED(
            0xE814), SENTIMENT_VERY_SATISFIED(
            0xE815), SETTINGS(
            0xE8B8), SETTINGS_APPLICATIONS(
            0xE8B9), SETTINGS_BACKUP_RESTORE(
            0xE8BA), SETTINGS_BLUETOOTH(
            0xE8BB), SETTINGS_BRIGHTNESS(
            0xE8BD), SETTINGS_CELL(
            0xE8BC), SETTINGS_ETHERNET(
            0xE8BE), SETTINGS_INPUT_ANTENNA(
            0xE8BF), SETTINGS_INPUT_COMPONENT(
            0xE8C0), SETTINGS_INPUT_COMPOSITE(
            0xE8C1), SETTINGS_INPUT_HDMI(
            0xE8C2), SETTINGS_INPUT_SVIDEO(
            0xE8C3), SETTINGS_OVERSCAN(
            0xE8C4), SETTINGS_PHONE(
            0xE8C5), SETTINGS_POWER(
            0xE8C6), SETTINGS_REMOTE(
            0xE8C7), SETTINGS_SYSTEM_DAYDREAM(
            0xE1C3), SETTINGS_VOICE(
            0xE8C8), SHARE(
            0xE80D), SHOP(
            0xE8C9), SHOP_TWO(
            0xE8CA), SHOPPING_BASKET(
            0xE8CB), SHOPPING_CART(
            0xE8CC), SHORT_TEXT(
            0xE261), SHOW_CHART(
            0xE6E1), SHUFFLE(
            0xE043), SIGNAL_CELLULAR_4_BAR(
            0xE1C8), SIGNAL_CELLULAR_CONNECTED_NO_INTERNET_4_BAR(
            0xE1CD), SIGNAL_CELLULAR_NO_SIM(
            0xE1CE), SIGNAL_CELLULAR_NULL(
            0xE1CF), SIGNAL_CELLULAR_OFF(
            0xE1D0), SIGNAL_WIFI_4_BAR(
            0xE1D8), SIGNAL_WIFI_4_BAR_LOCK(
            0xE1D9), SIGNAL_WIFI_OFF(
            0xE1DA), SIM_CARD(
            0xE32B), SIM_CARD_ALERT(
            0xE624), SKIP_NEXT(
            0xE044), SKIP_PREVIOUS(
            0xE045), SLIDESHOW(
            0xE41B), SLOW_MOTION_VIDEO(
            0xE068), SMARTPHONE(
            0xE32C), SMOKE_FREE(
            0xEB4A), SMOKING_ROOMS(
            0xEB4B), SMS(
            0xE625), SMS_FAILED(
            0xE626), SNOOZE(
            0xE046), SORT(
            0xE164), SORT_BY_ALPHA(
            0xE053), SPA(
            0xEB4C), SPACE_BAR(
            0xE256), SPEAKER(
            0xE32D), SPEAKER_GROUP(
            0xE32E), SPEAKER_NOTES(
            0xE8CD), SPEAKER_NOTES_OFF(
            0xE92A), SPEAKER_PHONE(
            0xE0D2), SPELLCHECK(
            0xE8CE), STAR(
            0xE838), STAR_BORDER(
            0xE83A), STAR_HALF(
            0xE839), STARS(
            0xE8D0), STAY_CURRENT_LANDSCAPE(
            0xE0D3), STAY_CURRENT_PORTRAIT(
            0xE0D4), STAY_PRIMARY_LANDSCAPE(
            0xE0D5), STAY_PRIMARY_PORTRAIT(
            0xE0D6), STOP(
            0xE047), STOP_SCREEN_SHARE(
            0xE0E3), STORAGE(
            0xE1DB), STORE(
            0xE8D1), STORE_MALL_DIRECTORY(
            0xE563), STRAIGHTEN(
            0xE41C), STREETVIEW(
            0xE56E), STRIKETHROUGH_S(
            0xE257), STYLE(
            0xE41D), SUBDIRECTORY_ARROW_LEFT(
            0xE5D9), SUBDIRECTORY_ARROW_RIGHT(
            0xE5DA), SUBJECT(
            0xE8D2), SUBSCRIPTIONS(
            0xE064), SUBTITLES(
            0xE048), SUBWAY(
            0xE56F), SUPERVISOR_ACCOUNT(
            0xE8D3), SURROUND_SOUND(
            0xE049), SWAP_CALLS(
            0xE0D7), SWAP_HORIZ(
            0xE8D4), SWAP_VERT(
            0xE8D5), SWAP_VERTICAL_CIRCLE(
            0xE8D6), SWITCH_CAMERA(
            0xE41E), SWITCH_VIDEO(
            0xE41F), SYNC(
            0xE627), SYNC_DISABLED(
            0xE628), SYNC_PROBLEM(
            0xE629), SYSTEM_UPDATE(
            0xE62A), SYSTEM_UPDATE_ALT(
            0xE8D7), TAB(
            0xE8D8), TAB_UNSELECTED(
            0xE8D9), TABLET(
            0xE32F), TABLET_ANDROID(
            0xE330), TABLET_MAC(
            0xE331), TAG_FACES(
            0xE420), TAP_AND_PLAY(
            0xE62B), TERRAIN(
            0xE564), TEXT_FIELDS(
            0xE262), TEXT_FORMAT(
            0xE165), TEXTSMS(
            0xE0D8), TEXTURE(
            0xE421), THEATERS(
            0xE8DA), THUMB_DOWN(
            0xE8DB), THUMB_UP(
            0xE8DC), THUMBS_UP_DOWN(
            0xE8DD), TIME_TO_LEAVE(
            0xE62C), TIMELAPSE(
            0xE422), TIMELINE(
            0xE922), TIMER(
            0xE425), TIMER_10(
            0xE423), TIMER_3(
            0xE424), TIMER_OFF(
            0xE426), TITLE(
            0xE264), TOC(
            0xE8DE), TODAY(
            0xE8DF), TOLL(
            0xE8E0), TONALITY(
            0xE427), TOUCH_APP(
            0xE913), TOYS(
            0xE332), TRACK_CHANGES(
            0xE8E1), TRAFFIC(
            0xE565), TRAIN(
            0xE570), TRAM(
            0xE571), TRANSFER_WITHIN_A_STATION(
            0xE572), TRANSFORM(
            0xE428), TRANSLATE(
            0xE8E2), TRENDING_DOWN(
            0xE8E3), TRENDING_FLAT(
            0xE8E4), TRENDING_UP(
            0xE8E5), TUNE(
            0xE429), TURNED_IN(
            0xE8E6), TURNED_IN_NOT(
            0xE8E7), TV(
            0xE333), UNARCHIVE(
            0xE169), UNDO(
            0xE166), UNFOLD_LESS(
            0xE5D6), UNFOLD_MORE(
            0xE5D7), UPDATE(
            0xE923), USB(
            0xE1E0), VERIFIED_USER(
            0xE8E8), VERTICAL_ALIGN_BOTTOM(
            0xE258), VERTICAL_ALIGN_CENTER(
            0xE259), VERTICAL_ALIGN_TOP(
            0xE25A), VIBRATION(
            0xE62D), VIDEO_CALL(
            0xE070), VIDEO_LABEL(
            0xE071), VIDEO_LIBRARY(
            0xE04A), VIDEOCAM(
            0xE04B), VIDEOCAM_OFF(
            0xE04C), VIDEOGAME_ASSET(
            0xE338), VIEW_AGENDA(
            0xE8E9), VIEW_ARRAY(
            0xE8EA), VIEW_CAROUSEL(
            0xE8EB), VIEW_COLUMN(
            0xE8EC), VIEW_COMFY(
            0xE42A), VIEW_COMPACT(
            0xE42B), VIEW_DAY(
            0xE8ED), VIEW_HEADLINE(
            0xE8EE), VIEW_LIST(
            0xE8EF), VIEW_MODULE(
            0xE8F0), VIEW_QUILT(
            0xE8F1), VIEW_STREAM(
            0xE8F2), VIEW_WEEK(
            0xE8F3), VIGNETTE(
            0xE435), VISIBILITY(
            0xE8F4), VISIBILITY_OFF(
            0xE8F5), VOICE_CHAT(
            0xE62E), VOICEMAIL(
            0xE0D9), VOLUME_DOWN(
            0xE04D), VOLUME_MUTE(
            0xE04E), VOLUME_OFF(
            0xE04F), VOLUME_UP(
            0xE050), VPN_KEY(
            0xE0DA), VPN_LOCK(
            0xE62F), WALLPAPER(
            0xE1BC), WARNING(
            0xE002), WATCH(
            0xE334), WATCH_LATER(
            0xE924), WB_AUTO(
            0xE42C), WB_CLOUDY(
            0xE42D), WB_INCANDESCENT(
            0xE42E), WB_IRIDESCENT(
            0xE436), WB_SUNNY(
            0xE430), WC(
            0xE63D), WEB(
            0xE051), WEB_ASSET(
            0xE069), WEEKEND(
            0xE16B), WHATSHOT(
            0xE80E), WIDGETS(
            0xE1BD), WIFI(
            0xE63E), WIFI_LOCK(
            0xE1E1), WIFI_TETHERING(
            0xE1E2), WORK(
            0xE8F9), WRAP_TEXT(
            0xE25B), YOUTUBE_SEARCHED_FOR(
            0xE8FA), ZOOM_IN(
            0xE8FF), ZOOM_OUT(
            0xE900), ZOOM_OUT_MAP(
            0xE56B);

    private static final String FONT_FAMILY = "MaterialIcons";
    private int codepoint;

    MaterialIcons(int codepoint) {
        this.codepoint = codepoint;
    }

    @Override
    public String getMIMEType() {
        return null;
    }

    @Override
    public String getFontFamily() {
        return FONT_FAMILY;
    }

    @Override
    public int getCodepoint() {
        return codepoint;
    }

    @Override
    public String getHtml() {
        return "<span class=\"v-icon " + FONT_FAMILY + "\">&#x" + Integer.toHexString(codepoint)
                + ";</span>";
    }

}
